### ISSUE TITLE
Scrape Metadata and URLs from CrossRef

### ISSUE THREAD

**Issue by tarrow** [ContentMine/getpapers#100]
We could add the crossref API as a place to query in the same way that Mark does for the daily crawl and as Peter has done for his recent work on Journal of Natural Products. We can get back the metadata json blob and save it like we do for the other APIs.

We can also parse the landing page URLs (which are all provided as dx.doi.org) from the JSON blob and then resolve these by making a call for each to dx.doi.org (I'm not sure there is a quicker way to pass somewhere a list of dois and resolve them all) and write out a list of URLs.

This list of URLs could then be passed to quickscrape.

I think this could probably be hacked together in a day and another api file.

**Comment by blahah** [comment]
already done, I just need time to merge it. also clone of #3 :)
