### ISSUE TITLE
Limit number of papers retrieved

### ISSUE THREAD

**Issue by psychemedia** [ContentMine/getpapers#102]
For testing particularly, it might be useful to be able to limit the number of papers retrieved, eg with a `--limit N` parameter?

**Comment by blahah** [comment]
hi @psychemedia, this feature exists already https://github.com/ContentMine/getpapers/blob/master/bin/getpapers.js#L39-L40 :)

```
--limit N
```

and 

```
-k N
```

should both work

**Comment by psychemedia** [comment]
I thought it might be but it's not listed in the [repo README](https://github.com/ContentMine/getpapers)?

**Comment by petermr** [comment]
It's in the help. Is there a way to update README from help?
