### ISSUE TITLE
CrossRef api doesn't obey -n

### ISSUE THREAD

**Issue by tarrow** [ContentMine/getpapers#105]
CrossRef should not download loads of metadata and certainly shouldn't write loads of things to disk if passed the minus -n flag. Currently it does; a lot of this is currently hidden in the crossref client (not written by us)

**Comment by blahah** [comment]
I think this is easily doable inside our code, I just forgot to implement it. If `--noexecute` is turned on, after the first response comes back we end the paging and also don't run any downloads.

**Comment by blahah** [comment]
I have a meeting now but if you haven't already done this I'm happy to do it. In general assign me any issues you want my help with.
