### ISSUE TITLE
QS hangs indefintely

### ISSUE THREAD

**Issue by petermr** [ContentMine/getpapers#109]
This URL has been retried and fails for ca 10 mins...
```
http://dx.doi.org/10.4172/2157-7471.1000s4-003
```

**Comment by blahah** [comment]
should be in the quickscrape repo?

**Comment by tarrow** [comment]
Yes, I will move it :)

**Comment by tarrow** [comment]
Issue moved to [ContentMine/quickscrape #81](https://github.com/ContentMine/quickscrape/issues/81) via [**ZenHub.io**](https://www.zenhub.io/)
