### ISSUE TITLE
Installing getpapers globally

### ISSUE THREAD

**Issue by abannachbrown** [ContentMine/getpapers#113]
There seems to be an issue with installing the getpapers. When i install the npm package globally (using the command "npm install -global getpapers") on windows 7 the cli hangs indefinitely (as shown). I have only noticed this problem today as it was working fine yesterday. 

The same issue occurs on another machine (running windows 10).
![hanging cli](https://cloud.githubusercontent.com/assets/19909504/16040698/31d7d812-3229-11e6-9b77-6c09332a78af.jpg)

**Comment by tarrow** [comment]
Hi!

Can you try with --global? (two minus signs)

**Comment by abananchbrown** [comment]
Hi
Thank you for the suggestion. The cli still hangs indefinitely. 
I've tried this also the other machine (windows 10) with the same result. 

![untitled1](https://cloud.githubusercontent.com/assets/19909504/16041657/88438c0a-322e-11e6-882f-86d89ba5d567.jpg)

**Comment by abananchbrown** [comment]
I think the issue might be with the latest update 0.4.6. 
getpapers v 0.4.5 has no issues installing.

**Comment by tarrow** [comment]
interesting.. How are you installing v0.4.5?

**Comment by chrissena** [comment]
I can confirm i have had exactly the same issue on windows 10. Have got it to work using

npm install --global getpapers@0.4.5

**Comment by abananchbrown** [comment]
i've installed v0.4.5 using the command npm install --gloabl getpapers@0.4.5
and can successfully execute a getpapers command and download full texts.

**Comment by tarrow** [comment]
I can replicate your problem on windows 7. I'll try and figure out what has
changed between the two versions and implement a fix. I guess it is some
bug in npm rather than on our side but perhaps we can find a workaround.

**Comment by tarrow** [comment]
Sorry that is has taken me a while to get to the bottom of this but I think the problem is that 0.4.6 is a bad release. I think lots of files have accidentally been packaged up with the release. Perhaps so many (or ones with such a long path name) that it breaks on windows.

I've asked @blahah to take a look at this and cut another release when he gets a chance.

**Comment by blahah** [comment]
Ah yes, looks like I accidentally included my testing files in the release. Sorry for the trouble. I'll cut another release now.

**Comment by blahah** [comment]
New version `0.4.7` pushed, with all the extra files removed. Can anyone with a Windows machine confirm whether this fixes the install issue?

**Comment by tarrow** [comment]
Yep! install issue all fixed! Thanks!
