### ISSUE TITLE
SciHub.cc getter/scraper for ContentMine?

### ISSUE THREAD

**Issue by brainstorm** [ContentMine/getpapers#116]
Nice project @blahah, @tarrow!

I've been looking at this project (and the accompanying modules `journal-scraper`, `quickscrape`, `norma`) and I've been wondering on whether adding a [sci-hub.cc](http://sci-hub.cc) module would be a good addition to the project or is it too tainted/controversial?

I'm almost convinced that the idea has crossed some minds over at some Hackathon/MozFest, but I'm not sure if it was ever "openly" discussed as a possibility or nice-to-have feature.

Thoughts?

**Comment by petermr** [comment]
We've had initial legal advice on this and any promotion of Sci-Hub could be seen as promoting a criminal activity which means that ContentMine could be prosecuted.  So if you develop a Sci-Hub scraper we wouldn't be allowed to mount it on this site. 

I have detailed my thoughts https://blogs.ch.cam.ac.uk/pmr/2016/05/06/sci-hub-and-my-personal-position-on-legality-6n/ and previous posts. 

I have deliberately no used Sci-Hub myself so don't know what a module would look like - I assume you mean a `getpapers` module like the `epmc` and `crossref` ones.

The code is licensed under Apache2 which puts no restriction on field of use.
