### ISSUE TITLE
Include alternative crossref api routes?

### ISSUE THREAD

**Issue by chartgerink** [ContentMine/getpapers#120]
Would it be possible to maybe add alternative API routes to the crossref query? It now all refers to base url `http://api.crossref.org/works` but an alternative I'd like to query is `http://api.crossref.org/prefixes/<prefix>/works`. 

All routes are available [here](https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md#combining-resource-components).

Would do a PR if I knew enough js but I don't. :-(

**Comment by petermr** [comment]
Can you use the `--filter` with `prefix`? That can be assembled without changing the code? But maybe it doesn't do the same or is inefficient

**Comment by chartgerink** [comment]
Stupid me. Yes, it just works. :-)
