### ISSUE TITLE
Query based on PMIDS

### ISSUE THREAD

**Issue by alexmaina** [ContentMine/getpapers#147]
I would like to bring your attention about the inability of getpapers to mine content using PMID.
For example, when i run a query using pmid

```
alex@alex-HP-ProDesk-600-G2-SFF:~$ getpapers -q PMID:27355041 -n -o maina
info: Searching using eupmc API
info: Running in no-execute mode, so nothing will be downloaded
error: Malformed or empty response from EuropePMC. Try running again. Perhaps your query is wrong.
```

When i run a query using PMCID, i get the following results

```
alex@alex-HP-ProDesk-600-G2-SFF:~$ getpapers -q PMCID:PMC5026053 -n -o maina
info: Searching using eupmc API
info: Running in no-execute mode, so nothing will be downloaded
info: Found 1 open access results
```

This [document](http://europepmc.org/docs/EBI_Europe_PMC_Web_Service_Reference.pdf) has listed PMID as a possible search field. Can getpapers search using PMIDS?

**Comment by tarrow** [comment]
Thanks for this report

It seems at first glance that this is a problem with EuropePMC (which getpapers depends upon)

You'll see that if you search for PMID:27355041 at europepmc.org it comes up blank. Let me investigate further though.

**Comment by tarrow** [comment]
It seems that at some point they stopped indexing by PMID and instead used the field EXT_ID (but this can also correspond to, for example, Agricola records)

This seems to work for me:
`getpapers -q EXT_ID:27355041 -o test`

Let me know if you have other problems

**Comment by alexmaina** [comment]
Thanks @tarrow it works very well but only where the PMID is for a paper that is Open access. Does this mean getpapers cannot mine titles and abstracts that are not open access in Pubmed/medline?

**Comment by tarrow** [comment]
Sure; you just need to use the `-a` flag to also get non-open access content. Often there isn't a fulltext available for these though.

**Comment by alexmaina** [comment]
Thanks again.....Last question and by no means least. I have a dataset of 10 PMIDS

```
+------------------+
| accession_number |
+------------------+
| 27747646         |
| 27649863         |
| 27621978         |
| 27478298         |
| 27441216         |
| 27397933         |
| 27386033         |
| 27382606         |
| 27379288         |
| 27355041         |
+------------------+
```
How can i query 10 PMIDS in a single script?

**Comment by tarrow** [comment]
We don't currently have a way to do this; but we probably should.

The easiest thing would be to simply write a bash script to call getpapers several times. Are you on a unix machine?

**Comment by tarrow** [comment]
I made a new issue for this: #148

**Comment by alexmaina** [comment]
Yes I am on a unix machine...is this the same for PMCIDs?
