### ISSUE TITLE
EuPMC API Broken - reported doesn't match actual results

### ISSUE THREAD

**Issue by tarrow** [ContentMine/getpapers#153]
Currently we fails out when trying to download from EuPMC. This seems to be an artefact of them updating to version 5.0.1 of their API. No release notes for this as of yet so we don't know what changed.

Unfortunately it seems to report more results than it returns. This means that we keep trying to get results until we time out.

For example http://www.ebi.ac.uk/europepmc/webservices/rest/search/query=FIRST_PDATE%3A2017-01-15%20OPEN_ACCESS%3Ay&resulttype=core&pageSize=1000&cursorMark=*

Says 170 results and actually only returns 168.

**Comment by blahah** [comment]
It should be possible to call a specific past version of the API when interacting with EUPMC - this would avoid API incompatibility issues.

**Comment by tarrow** [comment]
Historically yes, but I believe they moved to single beta/deprecated layout
although I'm struggling to find where this is documented.

FYI http://europepmc.org/RestfulWebService#oview

"Two versions of the RESTful web service are simultaneously available. This
approach to release management allows users to prepare for a new version,
rather than having to immediately respond to a version change. The details
of web service releases will be communicated to all known users. A mailing
list is compiled from users that have supplied an address in the 'email'
parameters of the 'search' and 'profile' modules. See the 'URL syntax'
section below for details on how different versions of the web service can
be accessed."

This time there was no test release first and no release notes. I've
already emailed them and they're 'looking into it' :) I'm not sure if they
meant to release (usually there is some notification to the mailing list
first).

**Comment by tarrow** [comment]
This was fixed by EuPMC
