### ISSUE TITLE
no-execute (dry-run) mode, -n

### ISSUE THREAD

**Issue by rossmounce** [ContentMine/getpapers#24]
My first test query using getpapers returned rather an unexpectedly large number of results (836), which it then proceeded to try and download...

I was wondering if getpapers could have a 'no-execute mode' -n similar to:

mmv -n
rsync -n

whereby the output would simply return the number of papers found for that query and NOT download anything. This is useful in the cases where you don't quite know how many matching papers you're going to get served.

**Comment by Blahah** [comment]
Good idea!
