### ISSUE TITLE
fulltext_html_urls.txt naming issue

### ISSUE THREAD

**Issue by rossmounce** [ContentMine/getpapers#41]
PMR and I think that the output fulltext_html_urls.txt should instead be named

APImethod_fulltext_html_urls.txt 

e.g. eupmc_fulltext_html_urls.txt , ieee_fulltext_html_urls.txt , arxiv_fulltext_html_urls.txt

This would better follow the convention set by the .json results files which are similarly named.
It's useful when you do a search for 'dinosaurs' in eupmc, then arxiv, then ieee all outputting into the same outdir

**Comment by Blahah** [comment]
good idea

**Comment by Blahah** [comment]
incidentally this should be simple to implement, and is something a new contributor could add
