### ISSUE TITLE
friendlier saving of log info to file [enhancement request]

### ISSUE THREAD

**Issue by rossmounce** [ContentMine/getpapers#43]
I know when I asked about this last time (for quickscrape) you suggested this to save the log output:   
```
command blah blah... 2>&1 | tee log.txt 
```

but that doesn't seem very friendly or intuitive for shell newbies. A lot of shell knowledge required.
Compare with wget inbuilt functionality   wget URL -o log.log

I for one would love to have an -o log-to-file option in both getpapers and quickscrape please :)

**Comment by Blahah** [comment]
OK, can you please open the matching issue on quickscrape?

**Comment by rossmounce** [comment]
OK, will do
