### ISSUE TITLE
Problem with fulltext html urls file - mostly empty

### ISSUE THREAD

**Issue by markmacgillivray** [ContentMine/getpapers#57]
Hi, I unfortunately have another problem to report with the fulltext html urls - maybe I am misunderstanding, but putting the details here just in case. An example query that ran for 14th September 2015 did return many URLs a few weeks ago, but I don't know which version of getpapers I was using then. However the same query can be seen to give odd results now:

getpapers --query 'FIRST_PDATE:2015-09-14 AND JOURNAL:"plos one"' --outdir '/home/cloo/test' 

with or without the --all flag gives the same result - two URLs appear on the fulltext html urls list.

But, looking at the eupmc_results.json, the first record in there is of course a PLOS one, and the URL listed for it is claimed to be subscription only. But, following the link, it is not. So, it seems that some URLs are now being incorrectly labelled as subscription only in some cases.

I'll get round this by parsing the eupmc_results.json directly anyway, but the issue may be problematic for people using getpapers directly.

**Comment by Blahah** [comment]
If URLs are being marked at subscription only, that's happening at the eupmc API. We don't change the data we get from the API, just output it to a file. I will double-check and email them if it's definitely an ongoing issue.

**Comment by markmacgillivray** [comment]
oh dear. Well at least it is not our code! Have a look at the output of some recent daily runs:

http://store.contentmine.org/daily20150929/eupmc_results.json

You can see that there are eupmc files in there marked as subscription but which are available open access on biomedcentral
