### ISSUE TITLE
only print out numbers of found papers

### ISSUE THREAD

**Issue by skasberger** [ContentMine/getpapers#62]
there should be a function, which prints out only the number of found publications for a query. not creating results.json or url_list.txt files, just outputting the numer for results for testing the dataset before downloading stuff. maybe this is better solved with ```$ wc``` after creating results.json and url_list.txt. or by just adding it to the end of getpapers command.

**Comment by Blahah** [comment]
This is the `--noexecute` flag, already implemented.

**Comment by skasberger** [comment]
it is not included in the help statement.

**Comment by Blahah** [comment]
What version are you running? The help statement is auto-generated from the options.

**Comment by Blahah** [comment]
Hmm, I may need to cut a new release - there are a bunch of commits since the last release. Right around the time I entered chronic sleep deprevation (parenthood)!

**Comment by skasberger** [comment]
https://github.com/ContentMine/getpapers/issues/63

**Comment by skasberger** [comment]
just to be on the same side: the number of papers found will be printed out before the download, but i think it would be nice to get the numbers if possible before downloading anything, but also after downloading results.json or more. this is especially the case for queries with a high of results.

**Comment by Blahah** [comment]
Yes - at the moment if you run a normal query it tells you how many results there are before downloading them. With noexecute the number of results is reported but no results are actually downloaded.

**Comment by skasberger** [comment]
nice. thats what i have meant.

**Comment by Blahah** [comment]
Excellent! Sorry for the terseness of my previous comments which were sent on mobile. Thanks for all the QC you've been doing :)
