### ISSUE TITLE
allow user to set a maximum number of results to retrieve

### ISSUE THREAD

**Issue by Blahah** [ContentMine/getpapers#65]
based on user feedback at a workshop (https://github.com/ContentMine/workshop-resources/issues/52)

**Comment by tarrow** [comment]
I had a little look and it doesn't seem like there is a quick way to advise people to add something to their EuropePMC query to limit results. I guess this would need to be added to the core code.

**Comment by Blahah** [comment]
That's right, and we want it to apply to all the APIs. So we just need to ensure that when we page through the results, we stop at the user provided limit.

**Comment by Blahah** [comment]
Implemented in #75 and included in release `0.4.3`
