### ISSUE TITLE
Inconsistent files in EPMC download

### ISSUE THREAD

**Issue by petermr** [ContentMine/getpapers#71]
I have used

```
getpapers -q Zika -p -x -o zika
```
and find that in some cases the PDF and XML are **completely** different papers. Examples: PMC4671560, PMC4637084 - can someone else confirm this is a problem?

This is possible EPMC, not `getpapers` but we should identify it.

**Comment by Blahah** [comment]
@petermr make sure you update to the latest version - I fixed a bug like this in the latest point release (`0.4.2`).

**Comment by tarrow** [comment]
Looked on EuropePMC. Think it gets the two files from:
http://www.ebi.ac.uk/europepmc/webservices/rest/PMC4671560/fullTextXML
and
http://europepmc.org/backend/ptpmcrender.fcgi?accid=PMC4671560&blobtype=pdf

These are both the same paper. I'll investigate further with getpapers and see if I can replicate.

**Comment by Blahah** [comment]
@tarrow this bug has been fixed, see my previous message. I suspect @petermr was using a previous version, which is why he experienced it. I left the issue open until he confirmed.

**Comment by petermr** [comment]
I can't seem to update:

localhost:lib pm286$ npm update getpapers
localhost:lib pm286$ getpapers --version
0.4.1

how do I force update? Do I have to checkout?


On Wed, Feb 17, 2016 at 5:35 PM, Richard Smith-Unna <
notifications@github.com> wrote:

> @tarrow <https://github.com/tarrow> this bug has been fixed, see my
> previous message. I suspect @petermr <https://github.com/petermr> was
> using a previous version, which is why he experienced it. I left the issue
> open until he confirmed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ContentMine/getpapers/issues/71#issuecomment-185317324>
> .
>



-- 
Peter Murray-Rust
Reader in Molecular Informatics
Unilever Centre, Dep. Of Chemistry
University of Cambridge
CB2 1EW, UK
+44-1223-763069

**Comment by Blahah** [comment]
just `npm install --global getpapers`
