### ISSUE TITLE
Downloads the first page of epmc + ieee results twice

### ISSUE THREAD

**Issue by tarrow** [ContentMine/getpapers#74]
I think we have a bug where we get the query page with and without page=1. I think this meant we always downloaded the first page of results twice but it also meant that we stopped one page early because we always had a full page of duplicates.

**Comment by Blahah** [comment]
Great catch :)

**Comment by tarrow** [comment]
I believe we have the same problem with ieee

**Comment by Blahah** [comment]
Closed in #75
