### ISSUE TITLE
provide instructions on how to download getpapers

### ISSUE THREAD

**Issue by teatree1212** [ContentMine/getpapers#88]
I wanted to use getpapers after attending the workshop about a month ago.  I forgot how to start but wanted to quickly write this as it was not documented anywhere ans I needed to reconstruct the process of how I finally managed to download getpapers. I didn't have wget installed, so I needed to do that. I did this by using homebrew and installing wget by brew install wget ( maybe convoluted but this is how it worked for me). then I used wget and the path for getpapers, but that was just a blind try to see whether this may work. I did find the path eventually ( it was a straight forward path). I know that this is a " new commandline user's " issue, but if you could document this issue for other people better, the first step to use your programmes is not such a big hurdle.

**Comment by blahah** [comment]
hi @teatree1212 , thanks for sharing this.

It seems like the trouble you had was installing `node` - is that right? Once you have `node`, installing `getpapers` should be as simple as `npm install --global getpapers`.

We should add some simple instructions for installing `node` - you can use `wget` or `curl`, and every unix system comes with one of these (OSX has `curl`, linux usually has `wget` or both).

**Comment by blahah** [comment]
fixed https://github.com/ContentMine/getpapers#installation
