### ISSUE TITLE
split `eumpc_results.json` into `metadata/source/metadata.json` for each `CTree`

### ISSUE THREAD

**Issue by petermr** [ContentMine/getpapers#97]
At present all EPMC metadata is in a single `cproject` file : `eupmc_results.json`.

Proposal: split this into a single `metadata.json` file for each `CTree`. Name:
```
<cproject>/<ctree>/metadata/source/metadata.json
```
A final `metadata/` directory will contain:
```
CTree/
    metadata/
        audit/
            metadata.json 
        article/
            metadata.json 
        derived/
            metadata.json 
        source/
            metadata.json 
```
see: contentmine/cmine#10

**Comment by tarrow** [comment]
eumc_result.json has been placed into individual CTrees since c0363a59
