### ISSUE TITLE
Error: ENOENT: no such file or directory, open '*/eupmc_result.json'

### ISSUE THREAD

**Issue by Daniel-Mietchen** [ContentMine/getpapers#99]
Triggered by Richard's talk at csvconf yesterday,
I gave the installation of ContentMine another try.

I went to
http://contentmine.org/
and from there via the "software" link to
https://contentmine.github.io/ ,
then
https://contentmine.github.io/osx.html ,
followed the instructions for getpapers.

When I then gave it a test run, I got

```
$ getpapers -q zika -o zika -x
info: Searching using eupmc API
info: Found 211 open access results
Retrieving results [==============================] 100% (eta 0.0s)
info: Done collecting results
info: Saving result metadata
info: Full EUPMC result metadata written to eupmc_results.json
fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'PMC4798858/eupmc_result.json'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.writeFileSync (fs.js:1327:33)
    at EuPmc.writeRecord
(~/.nvm/versions/node/v6.0.0/lib/node_modules/getpapers/lib/eupmc.js:556:6)
    at /Users/danielmietchen/.nvm/versions/node/v6.0.0/lib/node_modules/getpapers/lib/eupmc.js:169:11
    at Array.forEach (native)
    at EuPmc.handleSearchResults
(~/.nvm/versions/node/v6.0.0/lib/node_modules/getpapers/lib/eupmc.js:168:20)
    at EuPmc.completeCallback
(~/.nvm/versions/node/v6.0.0/lib/node_modules/getpapers/lib/eupmc.js:113:11)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
```

(I replaced my working directory with a tilde).

I poked around the documentation quite a bit, dealt with the creation
of a missing  package.json as per the instructions at
https://docs.npmjs.com/getting-started/using-a-package.json
and was lost in
https://github.com/ContentMine/workshop-resources/tree/master/software-tutorials/getpapers#tutorial
because "After starting the VM" had no instructions on how to start
the VM (or even which), and
https://github.com/ContentMine/workshop-resources/blob/master/software-tutorials/vms/README.md
did not seem to solve that either.

Can you (a) tell me what I am doing wrong and how to fix it, (b) check
the workflow that newbies are supposed to follow to get started?

I agree things have improved quite a bit since my last try around
Christmas, but it's a pity it still does not work for me.

Thanks and cheers.

**Comment by blahah** [comment]
Hi Daniel,

Thanks for trying getpapers and reporting the bug. This was introduced by me racing to get ready for my talk and a fix was pushed shortly after - can you try reinstalling:

```
npm install --global getpapers
```

now running the same command should just work:

```
getpapers -q zika -o zika -x
```

**Comment by Daniel-Mietchen** [comment]
Thanks - that query works now. Have yet to check out the rest of the pipeline.

**Comment by blahah** [comment]
@Daniel-Mietchen I recommend re-running with just

```
getpapers --query zika --output zika --minedterms
```

Which will add some pre-mined data.
